runtime: custom
env: flex
runtime_config:
  docker:
    image: europe-west3-docker.pkg.dev/etech-server/etech-repository/etech
handlers:
  - url: /.*
    script: this field is required, but ignored
manual_scaling:
  instances: 1