runtime: custom
env: flex
runtime_config:
  docker:
    image: europe-west3-docker.pkg.dev/etech-server/etech-repository/etech
handlers:
  - url: /.*
    script: this field is required, but ignored
    http_headers:
      Access-Control-Allow-Origin: "http://localhost:5173", "https://etechcli.netlify.app"
      Access-Control-Allow-Methods: "GET, POST, PUT, DELETE"
      Access-Control-Allow-Headers: "Content-Type, Authorization"
      Access-Control-Allow-Credentials: true
manual_scaling:
  instances: 1